### ISSUE TITLE
where could I download the dataset?

### ISSUE THREAD

**Issue by Baileyswu** [iondel/amdtk#19]
files like *.fea is not usual in my fields. Could you please offer me a link to download? Thanks a lot!

**Comment by lucasondel** [comment]
This project is ended and I would recommend to use my new toolkit (https://github.com/beer-asr/beer) which implements the same model and incorporates the features extraction (*.fea files) from WAV files.

**Comment by Baileyswu** [comment]
appreciate your share!!
